repos:
    -   repo: https://github.com/pycqa/isort
        rev: 5.5.2
        hooks:
        - id: isort
          additional_dependencies: ["toml"]
    -   repo: https://github.com/ambv/black
        rev: stable
        hooks:
        - id: black
          language_version: python3.8
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.3.0
        hooks:
        - id: flake8
        - id: check-yaml