name: job-portal

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # install testing dev libraries
          pip install -r requirements-test.txt
      - name: Run flake8 linter
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --exclude="migrations" --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --exclude="migrations" --statistics
      - name: Run black code formatter
        run: |
          black --check --line-length=120 --force-exclude=./*/migrations/ ./
